### ISSUE TITLE
There aren't any iris vectors or other content output.

### ISSUE THREAD

**Issue by CrushDemo01** [tensorsense/LaserGaze#2]
Hello, I'm nice to have allowed up the whole project and can use the camera input.
But I didn't find any output, including the video, nor any visual output (like the green line in the example).
Until I interrupted the program.

`python main.py`

The display on the terminal is as follows:

```
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1723543843.097827       1 gl_context.cc:344] GL version: 2.1 (2.1 INTEL-22.5.11), renderer: Intel(R) Iris(TM) Plus Graphics OpenGL Engine
W0000 00:00:1723543843.098798       1 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
^CTraceback (most recent call last):
  File "/xxx/yyy/zzz/LaserGaze-main/main.py", line 33, in <module>
    loop.run_until_complete(main())
  File "/xxx/yyy/miniconda3/envs/laser/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/xxx/yyy/miniconda3/envs/laser/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/xxx/yyy/miniconda3/envs/laser/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/xxx/yyy/miniconda3/envs/laser/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/xxx/yyy/zzz/LaserGaze-main/main.py", line 28, in main
    await gp.start()
  File "/xxx/yyy/zzz/LaserGaze-main/GazeProcessor.py", line 66, in start
    success, frame = cap.read()
KeyboardInterrupt
```

**Comment by ceyxasm** [comment]
Found the solution to this:
In EyeballDetector.py tweak the confidence scores
The default values are inflated in my opinion
I used these values and it worked just fine

```
class EyeballDetector:
    def __init__(self, initial_eye_center,
                 initial_eye_radius=0.02,
                 min_confidence=0.5, # originally 0.998
                 reasonable_confidence=0.5, # originally 0.997
                 points_threshold=300,
                 points_history_size=400,
                 refresh_time_threshold=10000):
```

**Comment by revanj** [comment]
> Found the solution to this: In EyeballDetector.py tweak the confidence scores The default values are inflated in my opinion I used these values and it worked just fine
> 
> ```
> class EyeballDetector:
>     def __init__(self, initial_eye_center,
>                  initial_eye_radius=0.02,
>                  min_confidence=0.5, # originally 0.998
>                  reasonable_confidence=0.5, # originally 0.997
>                  points_threshold=300,
>                  points_history_size=400,
>                  refresh_time_threshold=10000):
> ```

Thank you so much. This worked well.
